# Generated by Django 3.1.6 on 2021-03-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAdmin',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destination.comment')),
            ],
            bases=('destination.comment',),
        ),
    ]
